#!/bin/bash
dir=/tmp/"$(md5sum <<< "$(realpath "$2")")"
if [ "$1" = "update" ]; then
  mkdir -p "$dir"
  rsync -avz . "$dir"
elif [ "$1" = "inot" ]; then
  mkdir -p "$dir"
  rsync -avz . "$dir"
  while true; do
    latexdiff "$dir/$2" "$2" > diff.tex
    pdflatex -interaction=nonstopmode -halt-on-error "diff.tex"
    killall -HUP mupdf
    inotifywait -qre close_write .
  done
fi
