#!/bin/bash
ln -s dotfiles/xinitrc ~/.xinitrc
ln -s dotfiles/userbashrc ~/.bashrc
ln -s dotfiles/Xdefaults ~/.Xdefaults
ln -s dotfiles/nvim ~/.nvim
ln -s .nvim/nvimrc ~/.nvimrc
ln -s dotfiles/screenshot ~/.screenshot

